---
ip: "192.168.53.53"
memory: 1024
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/workspace
      to: /home/vagrant/sites

sites:
    - map: accuglassproducts.local
      to: /home/vagrant/sites/accuglass/code

databases:
    - accuglass_live
